# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Test and Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    
    - uses: actions/checkout@v4
    
    - name: Executa Node.js 
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'
    - run: npm ci
    - run: npm install
    - run: npm fund
    
    - name: Executa NPX para TailwindCSS e Minify
      uses: mikeal/npx@1.0.0
    - run: npx tailwindcss -i ./input.css -o ./output.css
    - run: npx minify ./index.html > ./index.min.css
    - run: npx minify ./output.css > ./output.min.css
    - run: sed -i "s/output.css/output.min.css/g" ./index.min.html
